### ISSUE TITLE
Building against 6.4+ kernel fails

### ISSUE THREAD

**Issue by claymen** [google/gasket-driver#12]
Building on an Ubuntu 22.04 system, on 6.3.4 it builds without issue, on 6.4.x it fails with the following. Same problem on 6.4.3, 6.4.2 and 6.4.1.

> DKMS make.log for gasket-1.0 for kernel 6.4.1-060401-generic (x86_64)
> Thu Jul 13 07:21:12 PM AWST 2023
> make: Entering directory '/usr/src/linux-headers-6.4.1-060401-generic'
> warning: the compiler differs from the one used to build the kernel
>   The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1) 12.3.0
>   You are using:           gcc-12 (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0
>   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_core.o
>   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_ioctl.o
>   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o
>   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_page_table.o
>   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_sysfs.o
>   CC [M]  /var/lib/dkms/gasket/1.0/build/apex_driver.o
> /var/lib/dkms/gasket/1.0/build/gasket_core.c: In function ‘gasket_register_device’:
> /var/lib/dkms/gasket/1.0/build/gasket_core.c:1841:41: error: passing argument 1 of ‘class_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
>  1841 |                 class_create(driver_desc->module, driver_desc->name);
>       |                              ~~~~~~~~~~~^~~~~~~~
>       |                                         |
>       |                                         struct module *
> In file included from ./include/linux/device.h:31,
>                  from ./include/linux/cdev.h:8,
>                  from /var/lib/dkms/gasket/1.0/build/gasket_core.h:11,
>                  from /var/lib/dkms/gasket/1.0/build/gasket_core.c:12:
> ./include/linux/device/class.h:230:54: note: expected ‘const char *’ but argument is of type ‘struct module *’
>   230 | struct class * __must_check class_create(const char *name);
>       |                                          ~~~~~~~~~~~~^~~~
> /var/lib/dkms/gasket/1.0/build/gasket_core.c:1841:17: error: too many arguments to function ‘class_create’
>  1841 |                 class_create(driver_desc->module, driver_desc->name);
>       |                 ^~~~~~~~~~~~
> ./include/linux/device/class.h:230:29: note: declared here
>   230 | struct class * __must_check class_create(const char *name);
>       |                             ^~~~~~~~~~~~
> cc1: some warnings being treated as errors
> make[1]: *** [scripts/Makefile.build:252: /var/lib/dkms/gasket/1.0/build/gasket_core.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
> make: *** [Makefile:2032: /var/lib/dkms/gasket/1.0/build] Error 2
> make: Leaving directory '/usr/src/linux-headers-6.4.1-060401-generic'

**Comment by claymen** [comment]
Tested again on a fresh Ubuntu 22.04 install and same results on 6.4.3

> DKMS make.log for gasket-1.0 for kernel 6.4.3-060403-generic (x86_64)
> Thu Jul 13 01:12:18 PM UTC 2023
> make: Entering directory '/usr/src/linux-headers-6.4.3-060403-generic'
> warning: the compiler differs from the one used to build the kernel
>   The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1) 12.3.0
>   You are using:           gcc-12 (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0
>   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_core.o
>   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_ioctl.o
>   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o
>   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_page_table.o
> /var/lib/dkms/gasket/1.0/build/gasket_core.c: In function ‘gasket_register_device’:
> /var/lib/dkms/gasket/1.0/build/gasket_core.c:1841:41: error: passing argument 1 of ‘class_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
>  1841 |                 class_create(driver_desc->module, driver_desc->name);
>       |                              ~~~~~~~~~~~^~~~~~~~
>       |                                         |
>       |                                         struct module *
> In file included from ./include/linux/device.h:31,
>                  from ./include/linux/cdev.h:8,
>                  from /var/lib/dkms/gasket/1.0/build/gasket_core.h:11,
>                  from /var/lib/dkms/gasket/1.0/build/gasket_core.c:12:
> ./include/linux/device/class.h:230:54: note: expected ‘const char *’ but argument is of type ‘struct module *’
>   230 | struct class * __must_check class_create(const char *name);
>       |                                          ~~~~~~~~~~~~^~~~
> /var/lib/dkms/gasket/1.0/build/gasket_core.c:1841:17: error: too many arguments to function ‘class_create’
>  1841 |                 class_create(driver_desc->module, driver_desc->name);
>       |                 ^~~~~~~~~~~~
> ./include/linux/device/class.h:230:29: note: declared here
>   230 | struct class * __must_check class_create(const char *name);
>       |                             ^~~~~~~~~~~~
> cc1: some warnings being treated as errors
> make[1]: *** [scripts/Makefile.build:252: /var/lib/dkms/gasket/1.0/build/gasket_core.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
> make: *** [Makefile:2032: /var/lib/dkms/gasket/1.0/build] Error 2
> make: Leaving directory '/usr/src/linux-headers-6.4.3-060403-generic'

And testing on 23.04 same mainline 6.4.3 kernel

> DKMS make.log for gasket-1.0 for kernel 6.4.3-060403-generic (x86_64)
> Thu Jul 13 01:12:11 PM UTC 2023
> make: Entering directory '/usr/src/linux-headers-6.4.3-060403-generic'
> warning: the compiler differs from the one used to build the kernel
>   The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1) 12.3.0
>   You are using:           gcc-12 (Ubuntu 12.2.0-17ubuntu1) 12.2.0
>   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_core.o
>   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_ioctl.o
>   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_page_table.o
>   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o
> /var/lib/dkms/gasket/1.0/build/gasket_core.c: In function ‘gasket_register_device’:
> /var/lib/dkms/gasket/1.0/build/gasket_core.c:1841:41: error: passing argument 1 of ‘class_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
>  1841 |                 class_create(driver_desc->module, driver_desc->name);
>       |                              ~~~~~~~~~~~^~~~~~~~
>       |                                         |
>       |                                         struct module *
> In file included from ./include/linux/device.h:31,
>                  from ./include/linux/cdev.h:8,
>                  from /var/lib/dkms/gasket/1.0/build/gasket_core.h:11,
>                  from /var/lib/dkms/gasket/1.0/build/gasket_core.c:12:
> ./include/linux/device/class.h:230:54: note: expected ‘const char *’ but argument is of type ‘struct module *’
>   230 | struct class * __must_check class_create(const char *name);
>       |                                          ~~~~~~~~~~~~^~~~
> /var/lib/dkms/gasket/1.0/build/gasket_core.c:1841:17: error: too many arguments to function ‘class_create’
>  1841 |                 class_create(driver_desc->module, driver_desc->name);
>       |                 ^~~~~~~~~~~~
> ./include/linux/device/class.h:230:29: note: declared here
>   230 | struct class * __must_check class_create(const char *name);
>       |                             ^~~~~~~~~~~~
> cc1: some warnings being treated as errors
> make[1]: *** [scripts/Makefile.build:252: /var/lib/dkms/gasket/1.0/build/gasket_core.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
> make: *** [Makefile:2032: /var/lib/dkms/gasket/1.0/build] Error 2
> make: Leaving directory '/usr/src/linux-headers-6.4.3-060403-generic'

**Comment by chrBrd** [comment]
The function signature for `class_create()` has been changed in 6.4 - see [here](https://github.com/torvalds/linux/commit/dcfbb67e48a2becfce7990386e985b9c45098ee5) for the relevant commit.

This will get the code to compile, and I don't expect it to break anything, but I be aware haven't tested this with hardware yet, and won't be able to for a few days:

```c
// `gasket_core.c`, line 1841:

// Change from this:
class_create(driver_desc->module, driver_desc->name);

// to this:
class_create(driver_desc->name);
```

**Comment by claymen** [comment]
Thank you for the fix, this is well outside my skillset, but had suspected there was some kind of fundamental change that was breaking it. I'll be able to give it a test later this evening and report back.

> The function signature for `class_create()` has been changed in 6.4 - see [here](https://github.com/torvalds/linux/commit/dcfbb67e48a2becfce7990386e985b9c45098ee5) for the relevant commit.
> 
> This will get the code to compile, and I don't expect it to break anything, but be aware haven't tested this with hardware yet, and won't be able to for a few days:
> 
> ```c
> // `gasket_core.c`, line 1841:
> 
> // Change from this:
> class_create(driver_desc->module, driver_desc->name);
> 
> // to this:
> class_create(driver_desc->name);
> ```
